import type { Metadata } from "next";
import { Geist, Open_Sans } from "next/font/google";
import "./globals.css";
import Providers from "@/components/providers";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const openSans = Open_Sans({
	variable: "--font-open-sans",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Úkolníček",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang="cs" suppressHydrationWarning>
				<body
					className={`${geistSans.variable} ${openSans.variable} antialiased`}
				>
					<Providers>{children}</Providers>
				</body>
			</html>
		</ClerkProvider>
	);
}
